### ISSUE TITLE
Disney Tarzan Ita not patched 

### ISSUE THREAD

**Issue by daloandrea** [alex-free/libcrypt-patcher#4] opened 2024-03-30 15:24 UTC
Ive been trying to patch Disney Tarzan in Italian, with no success did i do anything wrong? Even because before this i patched Crash Bash which is working perfectly. Is the libcrypt patcher need to be in the same folder of the .bin / .cue files?
Thanks for your help

**Comment by alex-free** [comment] 2024-03-31 12:08
> Ive been trying to patch Disney Tarzan in Italian, with no success did i do anything wrong? Even because before this i patched Crash Bash which is working perfectly. Is the libcrypt patcher need to be in the same folder of the .bin / .cue files? Thanks for your help

Seems to be working correctly for me, what issue exactly is occurring?

You don't need to have the patcher in the same directory  of the bin file.
![Screenshot from 2024-03-31 08-06-33](https://github.com/alex-free/libcrypt-patcher/assets/72545918/4fbaaf9c-8ce9-469e-b4e0-9f3609f68fb9)

**Comment by alex-free** [comment] 2024-04-02 19:11
@daloandrea let me know how I can assist further to get this issue closed

**Comment by daloandrea** [comment] 2024-04-05 10:07
Hi @alex-free thank you for your support, at the moment im not at home where my actual ps1 is, if i try the patched game on duck station is ok? O is duck station autopatching the game?
Thanks

**Comment by alex-free** [comment] 2024-04-06 15:42
> Hi @alex-free thank you for your support, at the moment im not at home where my actual ps1 is, if i try the patched game on duck station is ok? O is duck station autopatching the game?
> Thanks 

Np, Duckstation works fine if you disable the advanced option "require sbi files".

**Comment by daloandrea** [comment] 2024-04-10 15:58
Tried again with your last update and no luck again ![IMG_20240410_165701.jpg](https://github.com/alex-free/libcrypt-patcher/assets/63473529/67290848-8403-4990-ad9d-a02049353745)

![IMG_20240410_165627.jpg](https://github.com/alex-free/libcrypt-patcher/assets/63473529/2b1219da-0ab3-413b-98b4-2b637bc9cf0c)

**Comment by alex-free** [comment] 2024-04-10 16:39
> Tried again with your last update and no luck again ![IMG_20240410_165701.jpg](https://github.com/alex-free/libcrypt-patcher/assets/63473529/67290848-8403-4990-ad9d-a02049353745)
> 
> ![IMG_20240410_165627.jpg](https://github.com/alex-free/libcrypt-patcher/assets/63473529/2b1219da-0ab3-413b-98b4-2b637bc9cf0c)
> 
> 

You need to disable the advanced setting option 'Require SBI Files' in advanced settings first of DuckStation. Looks like it's working correctly

**Comment by daloandrea** [comment] 2024-04-10 17:44
I have same settings the only thing is the tick on "Allow Booting without SBI file", is ok for duck station but my concern is, if I burn in a cd, it will be playable on the actual ps1?

**Comment by alex-free** [comment] 2024-04-11 00:47
> I have same settings the only thing is the tick on "Allow Booting without SBI file", is ok for duck station but my concern is, if I burn in a cd, it will be playable on the actual ps1? 

Yes it behaves the exact same way

**Comment by alex-free** [comment] 2024-04-24 02:26
So I confirmed... unpatched game if you use [level select](https://gamefaqs.gamespot.com/pc/198892-disneys-tarzan-action-game/cheats) to go to level 5 (adult change from kid) then it crashes. If you use my patcher it works fine. Closing this issue.

**Closed by alex-free** 2024-04-24 02:26 UTC
